### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chandu0101** [scalajs-react-interface/support#1]
Things to do before first release 

* [ ] Documentation

* [ ] More Tests 

* [ ] Templates for web,mobile,web-native

* [ ] Ditch current routers! and wrap `react-navigation` -  [not available yet ETA - January](https://github.com/facebook/react-native/wiki/Roadmap#core-libraries)

**Comment by Andrei-Pozolotin** [comment]
akka calls this "meta" https://github.com/akka/akka-meta

**Comment by chandu0101** [comment]
react calls `future` - https://github.com/reactjs/react-future , definitely we'll move to new repo for design/development discussion . and use `support(this repo)` for end users issues,.. etc.

**Comment by chandu0101** [comment]
@Andrei-Pozolotin  https://github.com/scalajs-react-interface/incubator/issues/2
